/** Typed auth error codes returned by the HTTP API and WS auth. */
export type AuthErrorCode =
  | 'INVALID_EMAIL'
  | 'INVALID_USERNAME'
  | 'USERNAME_RESERVED'
  | 'INVALID_DISPLAY_NAME'
  | 'INVALID_AVATAR'
  | 'WEAK_PASSWORD'
  | 'EMAIL_ALREADY_EXISTS'
  | 'USERNAME_ALREADY_EXISTS'
  | 'INVALID_CREDENTIALS'
  | 'ACCOUNT_LOCKED'
  | 'ACCOUNT_DELETED'
  | 'SESSION_EXPIRED'
  | 'SESSION_REVOKED'
  | 'INVALID_REFRESH_TOKEN'
  | 'INVALID_ACCESS_TOKEN'
  | 'INVALID_RESET_TOKEN'
  | 'RESET_TOKEN_EXPIRED'
  | 'RATE_LIMITED'
  | 'INVALID_REQUEST'
  | 'NOT_AUTHENTICATED'
  | 'FORBIDDEN'
  | 'INTERNAL_ERROR';

export const AUTH_ERROR_STATUS: Record<AuthErrorCode, number> = {
  INVALID_EMAIL: 400,
  INVALID_USERNAME: 400,
  USERNAME_RESERVED: 400,
  INVALID_DISPLAY_NAME: 400,
  INVALID_AVATAR: 400,
  WEAK_PASSWORD: 400,
  EMAIL_ALREADY_EXISTS: 409,
  USERNAME_ALREADY_EXISTS: 409,
  INVALID_CREDENTIALS: 401,
  ACCOUNT_LOCKED: 423,
  ACCOUNT_DELETED: 401,
  SESSION_EXPIRED: 401,
  SESSION_REVOKED: 401,
  INVALID_REFRESH_TOKEN: 401,
  INVALID_ACCESS_TOKEN: 401,
  INVALID_RESET_TOKEN: 400,
  RESET_TOKEN_EXPIRED: 400,
  RATE_LIMITED: 429,
  INVALID_REQUEST: 400,
  NOT_AUTHENTICATED: 401,
  FORBIDDEN: 403,
  INTERNAL_ERROR: 500,
};

export class AuthError extends Error {
  readonly code: AuthErrorCode;
  readonly status: number;
  constructor(code: AuthErrorCode, message?: string) {
    super(message ?? code);
    this.code = code;
    this.status = AUTH_ERROR_STATUS[code];
  }
}
